name: laundriin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

   # UI
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  dashed_line: ^0.1.0+3
  carousel_slider: ^5.0.0
  dotted_line: ^3.2.3
  font_awesome_flutter: ^10.8.0
  flutter_widget_from_html: ^0.15.2
  grouped_list: ^6.0.0
  shimmer: ^3.0.0
  flutter_lazy_indexed_stack: ^0.0.6
  with_space_between: ^0.0.2
  table_calendar: ^3.1.0
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  modal_bottom_sheet: ^3.0.0
  webview_flutter: ^4.10.0
  camera: ^0.11.0+2
  photo_view: ^0.14.0
  flutter_html: ^3.0.0

  # dropdown
  dropdown_search: ^6.0.2

  # maps
  google_maps_flutter: ^2.11.0
  geolocator: ^14.0.2

  # Firebase
  firebase_messaging: ^16.0.4
  firebase_crashlytics: ^5.0.5
  firebase_database: ^12.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  # flutter_local_notifications: ^19.5.0

  # utilities
  permission_handler: ^11.0.1
  device_info_plus: ^11.1.1
  collection: ^1.18.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  intl: ^0.20.2
  image_picker: ^1.2.1
  super_tooltip: ^2.0.8
  open_file: ^3.5.3
  file_picker: ^8.1.2
  encrypt: ^5.0.3
  envied: ^1.0.0
  dotted_decoration: ^2.0.0
  path_provider: ^2.1.4
  flutter_downloader: ^1.11.8
  equatable: ^2.0.5
  flutter_pdfview: ^1.4.0
  path: ^1.9.0
  jiffy: ^6.3.2
  http: ^1.2.0
  image: ^4.1.0

  # Transision & Animation
  page_transition: ^2.2.1



  # State Management
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2

  # Code generation
  json_annotation: ^4.9.0

  # Service locator
  get_it: ^8.0.2

  # User Preference & Local storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1


  # Networking
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.4.1
  awesome_dio_interceptor: ^1.0.0
  socket_io_client: ^3.0.2
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  marquee: ^2.3.0
  location: ^8.0.1
  change_app_package_name: ^1.5.0
  apple_maps_flutter: ^1.4.0
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  flutter_fortune_wheel: ^1.3.2
  flutter_flavorizr: ^2.4.1
  cloudinary_api: ^1.1.1
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  # networking
  retrofit_generator: ^9.1.5

  # env
  envied_generator: ^1.0.0

  # Code generation
  build_runner: ^2.4.15
  json_serializable: ^6.8.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  config:
    enable-swift-package-manager: false

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DIN14
      fonts:
        - asset: assets/fonts/DIN14_Bold.otf
          weight: 700
        - asset: assets/fonts/DIN14_Extra-Light.otf
          weight: 300
        - asset: assets/fonts/DIN14_Regular.otf
          weight: 400
        - asset: assets/fonts/DIN14_Demi.otf
          weight: 600


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
